name: 📚 Documentation Issue
description: Report an issue with documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation! 📚
        
        Clear documentation is crucial for project adoption and success.

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: What file or page has the issue?
      placeholder: e.g., README.md, docs/architecture.md, API documentation
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Typo/Grammar
        - Unclear explanation
        - Missing information
        - Outdated content
        - Broken link
        - Missing examples
        - Incorrect code sample
        - Missing API documentation
        - Installation issues
        - Architecture unclear

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue in detail
      placeholder: What's wrong with the current documentation?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How do you think this should be fixed or improved?
      placeholder: Your suggestion for improvement...

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is primarily affected by this documentation issue?
      multiple: true
      options:
        - New users/beginners
        - Experienced developers
        - System administrators
        - Researchers
        - API consumers
        - Contributors
        - DevOps engineers

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Offer
      description: Would you like to help fix this documentation issue?
      options:
        - label: I can submit a PR to fix this
        - label: I can provide better examples
        - label: I can help with technical review
