# Advanced 5G OpenRAN Cognitive Intelligence Configuration
# ==========================================================

# System Configuration
system:
  name: "AI-Powered 5G OpenRAN Optimizer"
  version: "2.0.0"
  environment: "production"  # development, staging, production
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  
# Real-time Processing
real_time:
  optimization_interval: 5.0  # seconds
  data_collection_frequency: 1.0  # seconds
  max_processing_latency: 10.0  # seconds
  buffer_size: 1000  # number of data points

# Cognitive Intelligence Engine
cognitive_engine:
  enable_quantum_optimization: true
  enable_neuromorphic: true
  enable_digital_twin: true
  enable_explainable_ai: true
  enable_autonomous_healing: true
  enable_cognitive_radio: true
  enable_intent_based: true
  
  # Quantum Computing
  quantum:
    backend: "qasm_simulator"
    shots: 1024
    max_qubits: 20
    
  # Digital Twin
  digital_twin:
    update_frequency: 0.1  # seconds
    fidelity_threshold: 0.95
    prediction_horizon: 300  # seconds
    
  # Autonomous Operations
  autonomous:
    healing_confidence_threshold: 0.85
    max_autonomous_actions: 5
    escalation_timeout: 300  # seconds

# Edge AI Intelligence
edge_ai:
  enable_edge_processing: true
  edge_latency_target: 1.0  # milliseconds
  edge_compute_budget: 100.0  # GFLOPS
  
  # Model Optimization
  model_optimization:
    enable_quantization: true
    quantization_bits: 8
    enable_pruning: true
    pruning_ratio: 0.3
    
  # Resource Management
  resource_management:
    power_budget_watts: 10.0
    memory_budget_mb: 8192
    cpu_budget_percent: 80.0
    
  # Federated Learning
  federated_learning:
    enable: true
    aggregation_frequency: 30.0  # seconds
    min_participants: 3
    max_participants: 20

# Network Security AI
security:
  enable_threat_detection: true
  enable_zero_trust: true
  enable_automated_response: true
  enable_privacy_preservation: true
  
  # Threat Detection
  threat_detection:
    sensitivity: 0.85
    anomaly_threshold: 0.95
    monitoring_window: 60.0  # seconds
    
  # Zero Trust
  zero_trust:
    trust_score_threshold: 0.7
    continuous_verification: true
    device_profiling: true
    
  # Automated Response
  automated_response:
    max_response_time: 5.0  # seconds
    escalation_levels:
      - "monitor"
      - "alert"
      - "isolate"
      - "block"
    
  # Privacy Protection
  privacy:
    anonymization_method: "differential_privacy"
    privacy_budget: 1.0
    data_retention_days: 30

# Advanced AI Optimizer
ai_optimizer:
  enable_multi_objective: true
  enable_reinforcement_learning: true
  enable_federated_learning: true
  enable_graph_neural_networks: true
  enable_transformer_models: true
  
  # Multi-Objective Optimization
  multi_objective:
    objectives:
      - "throughput"
      - "latency"
      - "energy_efficiency"
      - "user_satisfaction"
    population_size: 100
    generations: 50
    
  # Reinforcement Learning
  reinforcement_learning:
    algorithm: "PPO"  # PPO, SAC, TD3
    learning_rate: 0.0003
    batch_size: 64
    episodes: 1000
    
  # Graph Neural Networks
  graph_neural_networks:
    layers: 3
    hidden_dim: 128
    dropout: 0.2
    learning_rate: 0.001

# Network Configuration
network:
  # 5G Network Slices
  network_slices:
    eMBB:  # Enhanced Mobile Broadband
      bandwidth_ghz: 100
      latency_req_ms: 20
      reliability: 0.99
      
    URLLC:  # Ultra-Reliable Low-Latency Communications
      bandwidth_ghz: 50
      latency_req_ms: 1
      reliability: 0.99999
      
    mMTC:  # Massive Machine Type Communications
      bandwidth_ghz: 10
      latency_req_ms: 100
      reliability: 0.95
      
  # Base Station Configuration
  base_stations:
    count: 20
    frequency_bands:
      - "sub6"
      - "mmwave"
    capacity_range:
      min: 500
      max: 1000
      
  # User Equipment
  user_equipment:
    count: 100
    service_types:
      - "eMBB"
      - "URLLC"
      - "mMTC"
    mobility_models:
      - "stationary"
      - "low_mobility"
      - "high_mobility"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  enable_cors: true
  enable_compression: true
  rate_limiting:
    requests_per_minute: 1000
    burst_size: 100
    
  # WebSocket
  websocket:
    max_connections: 1000
    heartbeat_interval: 30
    message_queue_size: 1000

# Dashboard Configuration
dashboard:
  host: "0.0.0.0"
  port: 8501
  theme: "dark"
  auto_refresh_seconds: 5
  max_data_points: 1000
  
  # Visualization
  charts:
    enable_3d: true
    enable_real_time: true
    animation_speed: 1000  # milliseconds

# Database Configuration
database:
  type: "postgresql"  # postgresql, mongodb, sqlite
  host: "localhost"
  port: 5432
  name: "5g_oran_optimizer"
  pool_size: 20
  max_overflow: 30
  
  # Time Series Database
  time_series:
    type: "influxdb"  # influxdb, prometheus
    host: "localhost"
    port: 8086
    retention_policy: "30d"

# Storage Configuration
storage:
  type: "filesystem"  # filesystem, s3, gcs, azure
  base_path: "./data"
  
  # Model Storage
  models:
    path: "./models"
    versioning: true
    compression: true
    
  # Data Storage
  data:
    path: "./data"
    format: "parquet"  # parquet, csv, json
    compression: "snappy"

# Monitoring & Observability
monitoring:
  enable_metrics: true
  enable_tracing: true
  enable_logging: true
  
  # Prometheus
  prometheus:
    enabled: true
    port: 9090
    scrape_interval: 15  # seconds
    
  # Grafana
  grafana:
    enabled: true
    port: 3000
    
  # Logging
  logging:
    level: "INFO"
    format: "json"
    rotation: "daily"
    retention_days: 30

# Performance Configuration
performance:
  # CPU
  cpu:
    max_threads: 8
    affinity: null  # CPU affinity list
    
  # Memory
  memory:
    max_memory_gb: 16
    cache_size_gb: 4
    
  # GPU
  gpu:
    enable: true
    device_ids: [0]  # GPU device IDs
    memory_fraction: 0.8

# Development & Testing
development:
  debug_mode: false
  profiling: false
  mock_data: false
  test_mode: false
  
  # Synthetic Data Generation
  synthetic_data:
    enabled: true
    seed: 42
    noise_level: 0.1
    
# Deployment Configuration
deployment:
  mode: "standalone"  # standalone, kubernetes, docker
  
  # Docker
  docker:
    image: "5g-oran-optimizer:latest"
    registry: "localhost:5000"
    
  # Kubernetes
  kubernetes:
    namespace: "5g-oran"
    replicas: 3
    resources:
      cpu: "2"
      memory: "4Gi"
      
  # Health Checks
  health_checks:
    enabled: true
    interval: 30  # seconds
    timeout: 10  # seconds
    retries: 3

# Security Configuration
security_config:
  # Authentication
  authentication:
    enabled: true
    method: "jwt"  # jwt, oauth, basic
    secret_key: "your-secret-key-change-this"
    token_expiry: 3600  # seconds
    
  # Authorization
  authorization:
    enabled: true
    roles:
      - "admin"
      - "operator"
      - "viewer"
      
  # Encryption
  encryption:
    algorithm: "AES-256-GCM"
    key_rotation_interval: 3600  # seconds
    
  # Rate Limiting
  rate_limiting:
    enabled: true
    requests_per_minute: 1000
    burst_size: 100
